### ISSUE TITLE
Invalid Version: 0.1.0rc2 when installing via Bower

### ISSUE THREAD

**Issue by glojek** [joaoneto/angular-bootstrap-select#27]
Attempt of installing 0.1.0-rc2 via Bower causes the following error:

```shell
bower install
bower angular-bootstrap-select#0.1.0-rc2       not-cached git://github.com/joaoneto/angular-bootstrap-select.git#0.1.0-rc2
bower angular-bootstrap-select#0.1.0-rc2          resolve git://github.com/joaoneto/angular-bootstrap-select.git#0.1.0-rc2
bower angular-bootstrap-select#0.1.0-rc2         download https://github.com/joaoneto/angular-bootstrap-select/archive/v0.1.0-rc2.tar.gz
bower angular-bootstrap-select#0.1.0-rc2          extract archive.tar.gz
bower angular-bootstrap-select#0.1.0-rc2            error Invalid Version: 0.1.0rc2

Stack trace:
TypeError: Invalid Version: 0.1.0rc2
    at new SemVer (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:273:11)
    at compare (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:460:10)
    at Object.neq (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:224:56)
    at GitHubResolver._savePkgMeta (/usr/local/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:131:53)
    at _fulfilled (/usr/local/lib/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/bower/node_modules/q/q.js:108:17)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.32
OS: Darwin 13.4.0 x64
```

**Comment by jbatalle** [comment]
Me too. Meanwhile, I'm working with 0.1.0rc1

**Comment by cdupoiron** [comment]
+1

**Comment by dkhunt27** [comment]
+1

**Comment by joaoneto** [comment]
:+1:
done!
